drop table if exists users CASCADE;
drop table if exists weekdays CASCADE;
drop table if exists tasks CASCADE;

CREATE TABLE IF NOT EXISTS users(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weekdays(
    name VARCHAR(20) NOT NULL,
    is_working_day BOOLEAN NOT NULL,
    time_start TIME NOT NULL,
    time_end TIME NOT NULL,
    is_night BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (name, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

create table if not exists tasks(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    duration int NOT NULL,
    is_only_night BOOLEAN NOT NULL,
    is_only_daytime BOOLEAN NOT NULL,
    periodicity VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    last_time DATE NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

