server:
  servlet:
    context-path: /smart-schedule

spring:
  application:
    name: Smart Schedule API
    version: 1.0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: smart_schedule
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    schemas: smart_schedule
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL}/auth/v1
          jwk-set-uri: ${SUPABASE_URL}/auth/v1/.well-known/jwks.json
logging:
  level:
    org.springframework.web: debug
    ru.aleksaosk: debug
    org.hibernate: info
    com.zaxxer: info
    org.springdoc: info


springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: true
  writer-with-order-by-keys: true
  override-with-generic-response: false