server:
  port: 8080
  base-url: http://localhost:8080
  servlet:
    context-path: /smart-schedule

spring:
  application:
    name: Smart Schedule API
    version: 1.0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.wvzrzlkszxthnmxwucji
    password: fBf-y5u-LB5-J49
logging:
  level:
    org.springframework.web: debug
    ru.aleksaosk: debug
    org.hibernate: info
    com.zaxxer: info
    org.springdoc: info


springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: true
  writer-with-order-by-keys: true
  override-with-generic-response: false